### ISSUE TITLE
Extension title is too dark and card size is too small.

### ISSUE THREAD

**Issue by lnogueir** [JacobLinCool/LeetCode-Stats-Card#12]
Hi,

I believe the recent updates to the repo caused some issues with the `extension=activity`, in particular when the theme is set to dark.

As you can see in the image below, the title is too dark, I think it would be better if it was a bit brighter.
Also, the last row in the activity is getting chopped off.
![image](https://user-images.githubusercontent.com/48890798/145309219-2853e3f8-047d-4cd2-94b4-5b00d4c3b771.png)

I will try making a pull request to fix those issues. However, I can't work on it till the weekend probably, but if you fix them before, that'd be great!

Thanks for the project!
Lucas

**Comment by JacobLinCool** [comment]
@lnogueir 

Thanks for your report.

The chopped last row problem is caused by the change of the default font. You can set `font` option to `Arial` (`font=Arial`) to fix that.

The color of extension title should be the same with `username`. The problem is caused by wrong config of `auto` theme (style). I will fix it as soon as possible.

**Comment by JacobLinCool** [comment]
The color of extension title should show normally now. https://github.com/JacobLinCool/LeetCode-Stats-Card/commit/542e2519e0fcf42b8d2902fa62a7e90f1eff6764

**Comment by lnogueir** [comment]
Looks just how I want with `font=sans-seriff`. Feel free to close this.
Thanks!
