### ISSUE TITLE
Is there Any way we can support leetcode-cn.com

### ISSUE THREAD

**Issue by fabian4** [JacobLinCool/LeetCode-Stats-Card#31]
Is there Any way we can support leetcode-cn.com

**Comment by fabian4** [comment]
ping @JacobLinCool

**Comment by JacobLinCool** [comment]
@fabian4 

Sorry for the late reply.

I think it is possible to support Leetcode-CN since they both provide GraphQL API.

The problem is that their data schemes are quite different, so it would need some work to "normalize" them.

I don't know if there is any package that can do this for us?

I would like to support that feature after I rewrite the messy codebase.

Thank for your advice.
