### ISSUE TITLE
Add a new option to display contest info. 

### ISSUE THREAD

**Issue by laporchen** [JacobLinCool/LeetCode-Stats-Card#50]
We could display user contest records with [LeetCode-Query](https://github.com/JacobLinCool/LeetCode-Query).
Maybe it could show the status like LeetCode User page.
<img width="855" alt="image" src="https://user-images.githubusercontent.com/31620109/175336388-9be4680d-d73f-4f4e-81c4-4ee8c69cc38d.png">
Or just lists out recent contest rank like recent activities.

**Comment by JacobLinCool** [comment]
@laporchen 
Thanks for your advice.

I would like to add an extension about contest ranking history in the future.

In the latest refactoring, the data layer will fetch the contest information by default (`us`).

For now, my plan is to use d3 for plotting the curve, but I am not familiar with it.

The data fetching function: https://github.com/JacobLinCool/LeetCode-Stats-Card/blob/7a0c2c23cc845cc7480d4ea80e1110ccc91c3308/src/core/query.ts#L6-L95

**Comment by JacobLinCool** [comment]
@laporchen 

I have created an extension of contest rating history and both of README and DEMO have been updated.

You may notice that the example in README is not me because I don't have enough contest data to show a meaningful graph.

Feel free to tell me about your comment on the extension, thanks!

**Comment by laporchen** [comment]
@JacobLinCool 

I tried to make some small changes to this extension. But I'm not sure about the method to test this locally.
I assume  is to change account_id in wrangler.toml and run npm dev.
But the process is exited due to the address is in use.
Not sure the exactly way to test this.

Here's the error message if you're interested in.
```
/Users/laporchen/Documents/Code/LeetCode-Stats-Card/node_modules/wrangler/wrangler-dist/cli.js:20495
            throw ex;
            ^

Error: listen EADDRINUSE: address already in use :::8976
    at Server.setupListenHandle [as _listen2] (node:net:1330:16)
    at listenInCluster (node:net:1378:12)
    at Server.listen (node:net:1465:7)
    at /Users/laporchen/Documents/Code/LeetCode-Stats-Card/node_modules/wrangler/wrangler-dist/cli.js:116922:12
    at new Promise (<anonymous>)
    at login (/Users/laporchen/Documents/Code/LeetCode-Stats-Card/node_modules/wrangler/wrangler-dist/cli.js:116866:24)
    at async loginOrRefreshIfRequired (/Users/laporchen/Documents/Code/LeetCode-Stats-Card/node_modules/wrangler/wrangler-dist/cli.js:116847:33)
    at async requireLoggedIn (/Users/laporchen/Documents/Code/LeetCode-Stats-Card/node_modules/wrangler/wrangler-dist/cli.js:117085:20)
    at async fetchInternal (/Users/laporchen/Documents/Code/LeetCode-Stats-Card/node_modules/wrangler/wrangler-dist/cli.js:117044:3)
    at async fetchResult (/Users/laporchen/Documents/Code/LeetCode-Stats-Card/node_modules/wrangler/wrangler-dist/cli.js:117116:16)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1357:8)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 8976
}
```

**Comment by JacobLinCool** [comment]
@laporchen 

`npm run dev` (or `pnpm dev`) is the correct way to run a dev server.

It seems that the port (8976) has been used by another program (or maybe another wrangler?)

wrangler's issues: https://github.com/cloudflare/wrangler2/issues?q=is%3Aissue+8976+is%3Aclosed

**Comment by JacobLinCool** [comment]
@laporchen 

Maybe the problem will be solved if you login (`wrangler login`) before starting the dev server?

**Comment by laporchen** [comment]
@JacobLinCool 
Yeah, that was the problem.

Now I'm trying to make animation for the graph and show contest name on each points when hover on it.
But it seems polyline does not support these stuffs. 
I tried animate tag to make animation but the result is mediocre and will start animation before it fades in.

The alternative solution I'm looking for right now may be [chart.js](https://www.chartjs.org/).
Chart.js seems to solve the both problems above. But I'm not sure can it work with the Item class or not.

**Comment by JacobLinCool** [comment]
@laporchen 

Um... I don't think chart.js (or other alternatives, such as echart) will be a solution.

Let me explain about some restrictions of SVG on GitHub:

1. No JavaScript. The restriction is not only being applied on GitHub, all SVG file in `<img>` tag will not be able to execute JavaScript because of security problems.
2. No external resources. All images, fonts and other assets must be inlined into the SVG itself because of the GitHub CSP.

As far as I know, all chart libraries are using JavaScript to make animations work. So, they are all not an option for our use case.
Currently the animation system is sucks. So we may have to design a good enough, extendable, and CSS only animation system.
You may want to see my opinion in #51.

If I misunderstand something, please let me know, thanks.
