### ISSUE TITLE
Can't render when it comes to leetcode.cn

### ISSUE THREAD

**Issue by CompetitiveLin** [JacobLinCool/LeetCode-Stats-Card#69]
`![Leetcode Stats](https://leetcard.jacoblin.cool/CompetitiveLin?theme=light&ext=heatmap&site=cn)` shows nothing.

Just like this below:

![Leetcode Stats](https://leetcard.jacoblin.cool/CompetitiveLin?theme=light&ext=heatmap&site=cn)

But https://leetcard.jacoblin.cool/CompetitiveLin?theme=light&ext=heatmap&site=cn works.

How to fix it?

**Comment by JacobLinCool** [comment]
I believe that it is caused by the slow response from leetcode.cn, which makes GitHub image proxy timeout.

I'm not sure what's the threshold of the timeout, maybe around 3 or 4 seconds because it always needs about 4.5 seconds to show up without any cache. (I use chrome dev-tool to measure it.)

My suggestion is to use GitHub Actions as a cron job to generate it. You can use the package [`leetcode-card`](https://www.npmjs.com/package/leetcode-card) or simply use curl to download the SVG and commit it to the repository.

**Comment by CompetitiveLin** [comment]
> I believe that it is caused by the slow response from leetcode.cn, which makes GitHub image proxy timeout.
> 
> I'm not sure what's the threshold of the timeout, maybe around 3 or 4 seconds because it always needs about 4.5 seconds to show up without any cache. (I use chrome dev-tool to measure it.)
> 
> My suggestion is to use GitHub Actions as a cron job to generate it. You can use the package [`leetcode-card`](https://www.npmjs.com/package/leetcode-card) or simply use curl to download the SVG and commit it to the repository.

You're using like a crawler to get those data and make a heatmap from leetcode.cn/graphql, are you?

**Comment by JacobLinCool** [comment]
Yes, the data are from the graphql endpoint.

You can find the details (of heat-map) at [here](https://github.com/JacobLinCool/LeetCode-Stats-Card/blob/main/src/core/exts/heatmap.ts).

**Comment by CompetitiveLin** [comment]
> 

haha no idea

**Comment by CompetitiveLin** [comment]
BTW, it works now.
