### ISSUE TITLE
Incorrect results

### ISSUE THREAD

**Issue by stevenewald** [JacobLinCool/LeetCode-Stats-Card#96]
Here's the link to my stat card: https://leetcard.jacoblin.cool/stevenewald

It shows 221 solved, but https://leetcode.com/stevenewald shows about 560 solved.

**Comment by JacobLinCool** [comment]
Wow, that's quite strange behavior! I will investigate this in the next few days. Thank you for reporting it.

**Comment by jaipatel248** [comment]
@stevenewald 
Faced the same issue.
I have 691 total solved problems but it shows 45 in the card.

The reason is in the API we are fetching only the current active session's stats.
The [PR](https://github.com/JacobLinCool/LeetCode-Stats-Card/pull/109) from @kevin-roman is the solution we are looking for.
